// sites/site-03-atelier-blanc/components/SiteFooter.vue
<template>
  <footer class="bg-blanc-light border-t border-blanc-accent/20 py-12 px-6">
    <div class="max-w-5xl mx-auto flex flex-col md:flex-row items-center justify-between gap-6">
      <!-- Logo -->
      <div class="text-center md:text-left">
        <p class="font-josefin text-blanc-primary text-xs tracking-[0.5em] font-light">atelier BLANC</p>
        <p class="font-jp text-blanc-muted text-xs mt-1">あなたらしさを、解放する場所。</p>
      </div>

      <!-- SNS -->
      <a
        href="#"
        aria-label="Instagram"
        class="text-blanc-muted hover:text-blanc-primary transition-colors duration-300"
      >
        <svg class="w-5 h-5" fill="currentColor" viewBox="0 0 24 24">
          <path d="M12 2.163c3.204 0 3.584.012 4.85.07 3.252.148 4.771 1.691 4.919 4.919.058 1.265.069 1.645.069 4.849 0 3.205-.012 3.584-.069 4.849-.149 3.225-1.664 4.771-4.919 4.919-1.266.058-1.644.07-4.85.07-3.204 0-3.584-.012-4.849-.07-3.26-.149-4.771-1.699-4.919-4.92-.058-1.265-.07-1.644-.07-4.849 0-3.204.013-3.583.07-4.849.149-3.227 1.664-4.771 4.919-4.919 1.266-.057 1.645-.069 4.849-.069zm0-2.163c-3.259 0-3.667.014-4.947.072-4.358.2-6.78 2.618-6.98 6.98-.059 1.281-.073 1.689-.073 4.948 0 3.259.014 3.668.072 4.948.2 4.358 2.618 6.78 6.98 6.98 1.281.058 1.689.072 4.948.072 3.259 0 3.668-.014 4.948-.072 4.354-.2 6.782-2.618 6.979-6.98.059-1.28.073-1.689.073-4.948 0-3.259-.014-3.667-.072-4.947-.196-4.354-2.617-6.78-6.979-6.98-1.281-.059-1.69-.073-4.949-.073zm0 5.838c-3.403 0-6.162 2.759-6.162 6.162s2.759 6.163 6.162 6.163 6.162-2.759 6.162-6.163c0-3.403-2.759-6.162-6.162-6.162zm0 10.162c-2.209 0-4-1.79-4-4 0-2.209 1.791-4 4-4s4 1.791 4 4c0 2.21-1.791 4-4 4zm6.406-11.845c-.796 0-1.441.645-1.441 1.44s.645 1.44 1.441 1.44c.795 0 1.439-.645 1.439-1.44s-.644-1.44-1.439-1.44z"/>
        </svg>
      </a>

      <!-- Copyright -->
      <p class="font-jp text-blanc-muted/60 text-xs">
        © {{ new Date().getFullYear() }} atelier BLANC. All rights reserved.
      </p>
    </div>
  </footer>
</template>

// sites/site-04-apex-gym/src/components/SiteFooter.tsx
const navItems = [
  { href: '#program', label: 'PROGRAM' },
  { href: '#why',     label: 'WHY APEX' },
  { href: '#trainer', label: 'TRAINER' },
  { href: '#price',   label: 'PRICE' },
];

export default function SiteFooter() {
  return (
    <footer className="bg-apex-bg border-t border-white/5 py-12 px-6">
      <div className="max-w-7xl mx-auto">
        <div className="grid grid-cols-1 md:grid-cols-3 gap-8 items-start mb-10">
          {/* Logo + address */}
          <div>
            <p className="font-oswald text-xl tracking-[0.3em] font-bold text-apex-primary mb-2">
              APEX <span className="text-apex-accent">GYM</span>
            </p>
            <p className="font-jp text-apex-secondary text-xs leading-loose">
              〒104-0061 東京都中央区銀座1-1-1 APEXビル2F<br />
              TEL: 03-1234-5678<br />
              営業時間: 6:00〜23:00（年中無休）
            </p>
          </div>

          {/* Nav */}
          <nav className="flex flex-col gap-3">
            {navItems.map(({ href, label }) => (
              <a
                key={href}
                href={href}
                className="font-barlow text-[11px] tracking-[0.25em] text-apex-secondary hover:text-apex-primary transition-colors duration-200 w-fit"
              >
                {label}
              </a>
            ))}
          </nav>

          {/* CTA */}
          <div>
            <p className="font-jp text-apex-secondary text-xs mb-4">
              まずは無料体験から始めませんか？<br />
              あなたの目標に向けて、一緒にスタートしましょう。
            </p>
            <a
              href="#cta"
              className="inline-block bg-apex-accent hover:bg-apex-accent-dark transition-colors duration-200 px-6 py-3 font-oswald text-[11px] tracking-[0.2em] text-white"
            >
              無料体験を申し込む
            </a>
          </div>
        </div>

        <div className="border-t border-white/5 pt-6 flex flex-col md:flex-row items-center justify-between gap-4">
          <p className="font-barlow text-apex-muted text-xs">
            © {new Date().getFullYear()} APEX GYM. All rights reserved.
          </p>
          <div className="flex gap-6">
            <a href="#" className="font-barlow text-[10px] tracking-wider text-apex-muted hover:text-apex-secondary transition-colors">
              PRIVACY POLICY
            </a>
            <a href="#" className="font-barlow text-[10px] tracking-wider text-apex-muted hover:text-apex-secondary transition-colors">
              TERMS
            </a>
          </div>
        </div>
      </div>
    </footer>
  );
}
