// sites/site-04-apex-gym/src/components/FlowSection.tsx
import { useInView } from '../hooks/useInView';

const steps = [
  {
    num:   '01',
    title: '無料カウンセリング予約',
    desc:  'フォームまたはLINEから24時間受付。48時間以内にご連絡します。',
  },
  {
    num:   '02',
    title: '無料体験トレーニング',
    desc:  '60分間の体験セッション。身体測定・現状分析・目標設定を行います。',
  },
  {
    num:   '03',
    title: 'プログラム・料金説明',
    desc:  'あなたの目標に合わせた最適なプログラムをご提案します。',
  },
  {
    num:   '04',
    title: 'ご入会・スタート',
    desc:  '入会手続き後、即日トレーニングを開始できます。',
  },
];

export default function FlowSection() {
  const { ref, inView } = useInView();

  return (
    <section className="bg-apex-bg py-24 md:py-36">
      <div className="max-w-7xl mx-auto px-6 lg:px-12">
        <div className="mb-16">
          <span className="font-oswald text-[11px] tracking-[0.4em] text-apex-accent uppercase">Flow</span>
          <h2
            className="font-oswald font-bold mt-2 text-apex-primary"
            style={{ fontSize: 'clamp(2.5rem, 6vw, 4.5rem)' }}
          >
            入会の流れ
          </h2>
        </div>

        <div ref={ref} className="grid grid-cols-1 md:grid-cols-4 gap-0 relative">
          {/* Connecting line (desktop) */}
          <div className="hidden md:block absolute top-8 left-[12.5%] right-[12.5%] h-px bg-apex-accent/25" />

          {steps.map((step, i) => (
            <div
              key={step.num}
              className={`relative text-center px-6 py-2 transition-all duration-500 ${
                inView ? 'opacity-100 translate-y-0' : 'opacity-0 translate-y-8'
              }`}
              style={{ transitionDelay: `${i * 130}ms` }}
            >
              {/* Step number circle */}
              <div className="w-16 h-16 rounded-full border-2 border-apex-accent flex items-center justify-center mx-auto mb-5 bg-apex-bg relative z-10">
                <span className="font-oswald font-bold text-apex-accent text-sm">{step.num}</span>
              </div>

              <h3 className="font-oswald text-sm font-bold text-apex-primary mb-3 leading-snug">
                {step.title}
              </h3>
              <p className="font-jp text-apex-secondary text-[11px] leading-loose">{step.desc}</p>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
}

// sites/site-03-atelier-blanc/components/FlowSection.vue
<script setup lang="ts">
const { target, inView } = useInView()

const steps = [
  { num: '01', title: 'ご予約',           desc: 'LINEまたはお電話にて。ご希望の日時をお伝えください。' },
  { num: '02', title: 'カウンセリング',    desc: 'ご来店後、ご希望・お悩みを丁寧に伺います。' },
  { num: '03', title: '施術',             desc: '完全個室でリラックスしながら施術をお受けいただけます。' },
  { num: '04', title: 'アフターフォロー', desc: 'ホームケアのアドバイスや次回のご提案をいたします。' },
]
</script>

<template>
  <section id="flow" class="bg-blanc-light py-28 md:py-40 px-6">
    <div ref="target" class="max-w-5xl mx-auto">

      <!-- Heading -->
      <div class="mb-16">
        <p :class="['reveal font-josefin text-[10px] tracking-[0.5em] text-blanc-accent mb-4', inView && 'in-view']">
          HOW IT WORKS
        </p>
        <h2 :class="['reveal reveal-delay-1 font-garamond text-4xl md:text-5xl italic font-light text-blanc-primary', inView && 'in-view']">
          Flow
        </h2>
      </div>

      <!-- Steps -->
      <div class="grid sm:grid-cols-2 lg:grid-cols-4 gap-0">
        <div
          v-for="(s, i) in steps"
          :key="s.num"
          :class="[
            'reveal',
            `reveal-delay-${i + 1}`,
            inView && 'in-view',
            'relative flex flex-col gap-5 p-8 border-t border-blanc-accent/30',
          ]"
        >
          <!-- Step number -->
          <span class="font-garamond text-5xl font-light text-blanc-accent/40 leading-none">{{ s.num }}</span>
          <div class="h-px w-8 bg-blanc-accent" />
          <h3 class="font-jp text-blanc-primary text-sm font-medium">{{ s.title }}</h3>
          <p class="font-jp text-blanc-muted text-xs leading-7">{{ s.desc }}</p>
        </div>
      </div>
    </div>
  </section>
</template>
