// sites/site-05-horizon-realestate/src/components/SiteFooter.tsx
import Link from 'next/link';

const navLinks = [
  { href: '/properties', label: '物件一覧' },
  { href: '/company',    label: '会社概要' },
  { href: '/contact',    label: 'お問い合わせ' },
];

export default function SiteFooter() {
  return (
    <footer className="bg-horizon-navy text-white">
      {/* Gold top line */}
      <div className="h-px bg-horizon-gold" />

      <div className="max-w-7xl mx-auto px-6 lg:px-12 py-16">
        <div className="grid grid-cols-1 md:grid-cols-3 gap-10 mb-12">
          {/* Logo + about */}
          <div className="md:col-span-1">
            <div className="mb-4">
              <p className="font-cormorant text-xl font-light tracking-[0.25em] text-white">HORIZON</p>
              <p className="font-sans-jp text-[9px] tracking-[0.4em] text-white/50 mt-0.5">不動産</p>
            </div>
            <p className="font-sans-jp text-xs text-white/50 leading-loose">
              地域に根ざして20年。<br />あなたの大切な住まい探しを、<br />丁寧にサポートします。
            </p>
          </div>

          {/* Navigation */}
          <div>
            <p className="font-cormorant text-xs italic tracking-[0.3em] text-horizon-gold mb-5">Navigation</p>
            <nav className="flex flex-col gap-3">
              {navLinks.map(({ href, label }) => (
                <Link
                  key={href}
                  href={href}
                  className="font-sans-jp text-xs text-white/60 hover:text-horizon-gold transition-colors duration-200"
                >
                  {label}
                </Link>
              ))}
            </nav>
          </div>

          {/* Contact */}
          <div>
            <p className="font-cormorant text-xs italic tracking-[0.3em] text-horizon-gold mb-5">Contact</p>
            <p className="font-cormorant text-2xl font-light text-white tracking-widest mb-1">03-1234-5678</p>
            <p className="font-sans-jp text-[10px] text-white/50 mb-4">9:00〜18:00（水・祝休）</p>
            <p className="font-sans-jp text-xs text-white/50 leading-loose">
              〒154-0000<br />
              東京都世田谷区三軒茶屋1-1-1<br />
              HORIZONビル3F
            </p>
          </div>
        </div>

        <div className="border-t border-white/10 pt-8 flex flex-col md:flex-row items-center justify-between gap-4">
          <p className="font-sans-jp text-[10px] text-white/30">
            © {new Date().getFullYear()} HORIZON不動産 All rights reserved.
          </p>
          <div className="flex gap-6">
            <a href="#" className="font-sans-jp text-[10px] text-white/30 hover:text-white/60 transition-colors">
              プライバシーポリシー
            </a>
            <a href="#" className="font-sans-jp text-[10px] text-white/30 hover:text-white/60 transition-colors">
              サイトマップ
            </a>
          </div>
        </div>
      </div>
    </footer>
  );
}

// sites/site-03-atelier-blanc/components/SiteFooter.vue
<template>
  <footer class="bg-blanc-light border-t border-blanc-accent/20 py-12 px-6">
    <div class="max-w-5xl mx-auto flex flex-col md:flex-row items-center justify-between gap-6">
      <!-- Logo -->
      <div class="text-center md:text-left">
        <p class="font-josefin text-blanc-primary text-xs tracking-[0.5em] font-light">atelier BLANC</p>
        <p class="font-jp text-blanc-muted text-xs mt-1">あなたらしさを、解放する場所。</p>
      </div>

      <!-- SNS -->
      <a
        href="#"
        aria-label="Instagram"
        class="text-blanc-muted hover:text-blanc-primary transition-colors duration-300"
      >
        <svg class="w-5 h-5" fill="currentColor" viewBox="0 0 24 24">
          <path d="M12 2.163c3.204 0 3.584.012 4.85.07 3.252.148 4.771 1.691 4.919 4.919.058 1.265.069 1.645.069 4.849 0 3.205-.012 3.584-.069 4.849-.149 3.225-1.664 4.771-4.919 4.919-1.266.058-1.644.07-4.85.07-3.204 0-3.584-.012-4.849-.07-3.26-.149-4.771-1.699-4.919-4.92-.058-1.265-.07-1.644-.07-4.849 0-3.204.013-3.583.07-4.849.149-3.227 1.664-4.771 4.919-4.919 1.266-.057 1.645-.069 4.849-.069zm0-2.163c-3.259 0-3.667.014-4.947.072-4.358.2-6.78 2.618-6.98 6.98-.059 1.281-.073 1.689-.073 4.948 0 3.259.014 3.668.072 4.948.2 4.358 2.618 6.78 6.98 6.98 1.281.058 1.689.072 4.948.072 3.259 0 3.668-.014 4.948-.072 4.354-.2 6.782-2.618 6.979-6.98.059-1.28.073-1.689.073-4.948 0-3.259-.014-3.667-.072-4.947-.196-4.354-2.617-6.78-6.979-6.98-1.281-.059-1.69-.073-4.949-.073zm0 5.838c-3.403 0-6.162 2.759-6.162 6.162s2.759 6.163 6.162 6.163 6.162-2.759 6.162-6.163c0-3.403-2.759-6.162-6.162-6.162zm0 10.162c-2.209 0-4-1.79-4-4 0-2.209 1.791-4 4-4s4 1.791 4 4c0 2.21-1.791 4-4 4zm6.406-11.845c-.796 0-1.441.645-1.441 1.44s.645 1.44 1.441 1.44c.795 0 1.439-.645 1.439-1.44s-.644-1.44-1.439-1.44z"/>
        </svg>
      </a>

      <!-- Copyright -->
      <p class="font-jp text-blanc-muted/60 text-xs">
        © {{ new Date().getFullYear() }} atelier BLANC. All rights reserved.
      </p>
    </div>
  </footer>
</template>
