// sites/site-04-apex-gym/src/components/SiteNav.tsx
import { useState, useEffect } from 'react';

const links = [
  { href: '#program', label: 'PROGRAM' },
  { href: '#why',     label: 'WHY APEX' },
  { href: '#trainer', label: 'TRAINER' },
  { href: '#price',   label: 'PRICE' },
];

export default function SiteNav() {
  const [scrolled, setScrolled] = useState(false);
  const [menuOpen, setMenuOpen] = useState(false);

  useEffect(() => {
    const onScroll = () => setScrolled(window.scrollY > 60);
    window.addEventListener('scroll', onScroll, { passive: true });
    return () => window.removeEventListener('scroll', onScroll);
  }, []);

  return (
    <nav
      className={`fixed top-0 left-0 right-0 z-50 transition-all duration-400 ${
        scrolled ? 'bg-apex-bg/96 backdrop-blur-sm border-b border-white/5' : 'bg-transparent'
      }`}
    >
      <div className="max-w-7xl mx-auto px-6 lg:px-12 h-16 flex items-center justify-between">
        {/* Logo */}
        <a href="#" className="font-oswald text-lg tracking-[0.35em] font-bold text-apex-primary">
          APEX <span className="text-apex-accent">GYM</span>
        </a>

        {/* Desktop links */}
        <ul className="hidden md:flex items-center gap-10">
          {links.map(({ href, label }) => (
            <li key={href}>
              <a
                href={href}
                className="font-barlow text-[11px] tracking-[0.25em] text-apex-secondary hover:text-apex-primary transition-colors duration-200"
              >
                {label}
              </a>
            </li>
          ))}
        </ul>

        {/* CTA */}
        <a
          href="#cta"
          className="hidden md:block bg-apex-accent hover:bg-apex-accent-dark transition-colors duration-200 px-5 py-2 font-oswald text-[11px] tracking-[0.2em] text-white"
        >
          無料体験
        </a>

        {/* Hamburger */}
        <button
          className="md:hidden flex flex-col gap-[5px] p-2"
          onClick={() => setMenuOpen(!menuOpen)}
          aria-label="メニュー"
        >
          <span
            className={`block w-6 h-[1px] bg-apex-primary transition-all duration-300 ${
              menuOpen ? 'rotate-45 translate-y-[6px]' : ''
            }`}
          />
          <span
            className={`block w-6 h-[1px] bg-apex-primary transition-all duration-200 ${
              menuOpen ? 'opacity-0' : ''
            }`}
          />
          <span
            className={`block w-6 h-[1px] bg-apex-primary transition-all duration-300 ${
              menuOpen ? '-rotate-45 -translate-y-[6px]' : ''
            }`}
          />
        </button>
      </div>

      {/* Mobile menu */}
      <div
        className={`md:hidden overflow-hidden transition-all duration-300 ${
          menuOpen ? 'max-h-72' : 'max-h-0'
        }`}
      >
        <div className="bg-apex-surface border-t border-white/5 px-6 py-6 flex flex-col gap-5">
          {links.map(({ href, label }) => (
            <a
              key={href}
              href={href}
              className="font-oswald text-sm tracking-[0.25em] text-apex-primary"
              onClick={() => setMenuOpen(false)}
            >
              {label}
            </a>
          ))}
          <a
            href="#cta"
            className="mt-2 bg-apex-accent text-center px-4 py-3 font-oswald text-sm tracking-[0.2em] text-white"
            onClick={() => setMenuOpen(false)}
          >
            無料体験を申し込む
          </a>
        </div>
      </div>
    </nav>
  );
}

// sites/site-03-atelier-blanc/components/SiteNav.vue
<script setup lang="ts">
const scrolled = ref(false)
const menuOpen = ref(false)

const links = [
  { label: 'Concept', href: '#concept' },
  { label: 'Service', href: '#service' },
  { label: 'Works',   href: '#works'   },
  { label: 'Reserve', href: '#reserve' },
  { label: 'Access',  href: '#access'  },
]

onMounted(() => {
  const onScroll = () => { scrolled.value = window.scrollY > 60 }
  window.addEventListener('scroll', onScroll, { passive: true })
  onUnmounted(() => window.removeEventListener('scroll', onScroll))
})
</script>

<template>
  <header
    :class="[
      'fixed top-0 left-0 right-0 z-50 transition-all duration-500',
      scrolled ? 'bg-blanc-bg/95 backdrop-blur-sm border-b border-blanc-accent/20' : 'bg-transparent',
    ]"
  >
    <div class="max-w-6xl mx-auto px-8 py-5 flex items-center justify-between">
      <a href="#" class="font-josefin text-blanc-primary text-xs tracking-[0.4em] font-light">
        atelier BLANC
      </a>

      <!-- Desktop -->
      <nav class="hidden md:flex gap-10">
        <a
          v-for="l in links"
          :key="l.label"
          :href="l.href"
          class="font-josefin text-[11px] tracking-[0.25em] text-blanc-muted hover:text-blanc-primary transition-colors duration-300"
        >
          {{ l.label }}
        </a>
      </nav>

      <!-- Mobile hamburger -->
      <button
        class="md:hidden flex flex-col gap-1.5 p-1"
        :aria-label="menuOpen ? 'メニューを閉じる' : 'メニューを開く'"
        @click="menuOpen = !menuOpen"
      >
        <span :class="['block w-5 h-px bg-blanc-primary transition-all duration-300', menuOpen ? 'rotate-45 translate-y-2' : '']" />
        <span :class="['block w-5 h-px bg-blanc-primary transition-all duration-300', menuOpen ? 'opacity-0' : '']" />
        <span :class="['block w-5 h-px bg-blanc-primary transition-all duration-300', menuOpen ? '-rotate-45 -translate-y-2.5' : '']" />
      </button>
    </div>

    <!-- Mobile menu -->
    <Transition name="slide">
      <div
        v-if="menuOpen"
        class="md:hidden bg-blanc-bg/98 border-t border-blanc-accent/20 px-8 py-8 flex flex-col gap-6"
      >
        <a
          v-for="l in links"
          :key="l.label"
          :href="l.href"
          class="font-josefin text-sm tracking-[0.25em] text-blanc-muted hover:text-blanc-primary transition-colors"
          @click="menuOpen = false"
        >
          {{ l.label }}
        </a>
      </div>
    </Transition>
  </header>
</template>

<style scoped>
.slide-enter-active, .slide-leave-active { transition: opacity 0.3s ease, transform 0.3s ease; }
.slide-enter-from, .slide-leave-to { opacity: 0; transform: translateY(-8px); }
</style>
